name: 'gitea-release-manger'
description: 'gitea-release-manger'
inputs:
  url:
    description: 'Git url'
    required: true
  token:
    description: 'Token fot gitea'
    required: true
  repository:
    description: 'Repository name'
    required: true
  command:
    description: 'Command'
    required: true
  tag:
    description: 'Tag'
    required: true
  path:
    description: 'Path to attachment'
    required: true
runs:
  using: 'node20'
  main: 'loader.js'